name: slave

on:
  workflow_call:
    inputs:
      version:
        description: version
        required: false
        type: string
      environment:
        description: environment
        required: true
        type: string

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: log variables from the master yml file
        run: echo "${{ inputs.version }} ${{ inputs.environment }}"
